import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// Pen paths used by the "Watch" writing tutorial.
///
/// Generated by `tool/gen_strokes.py` from the Mallige glyph skeletons and
/// normalised to each glyph's ink box (0..1). They show one sensible way to
/// draw the shape; they are not a verified traditional stroke order.
class StrokeGuide {
  StrokeGuide._();

  static Map<String, List<List<Offset>>> _letters = const {};

  /// Loads `assets/data/strokes.json`; the app works without it.
  static Future<void> load() async {
    try {
      loadFromJson(await rootBundle.loadString('assets/data/strokes.json'));
    } catch (e) {
      debugPrint('Stroke guide unavailable: $e');
    }
  }

  /// Parses the strokes JSON. Exposed for tests.
  static void loadFromJson(String raw) {
    final j = jsonDecode(raw) as Map<String, dynamic>;
    _letters = {
      for (final e in (j['letters'] as Map<String, dynamic>).entries)
        e.key: [
          for (final s in e.value as List)
            [
              for (final p in s as List)
                Offset(
                  ((p as List)[0] as num).toDouble(),
                  (p[1] as num).toDouble(),
                ),
            ],
        ],
    };
  }

  /// Normalised strokes for a letter (by its Kannada source), if known.
  static List<List<Offset>>? forLetter(String? kannada) =>
      kannada == null ? null : _letters[kannada];

  /// Maps normalised [strokes] onto [box] (the glyph's ink bounds).
  static List<List<Offset>> mapToRect(List<List<Offset>> strokes, Rect box) => [
    for (final s in strokes)
      [
        for (final p in s)
          Offset(box.left + p.dx * box.width, box.top + p.dy * box.height),
      ],
  ];
}
