"""Regenerates lib/astro/tables.dart from the VSOP87D Earth series and
Meeus' Table 47.A/47.B (via the pymeeus package: `pip install pymeeus`).

Terms of VSOP87 with amplitude below 5e-8 rad (~0.01") are dropped; the
truncation changes the Sun's longitude by well under one arc-second.
"""
from pymeeus import Earth, Moon

MIN_AMP = 5.0  # in units of 1e-8 rad (or 1e-8 AU for R)


def series(name, table):
    out = [f'const List<List<List<double>>> {name} = [']
    for power in table:
        out.append('  [')
        for a, b, c in power:
            if a >= MIN_AMP:
                out.append(f'    [{a!r}, {b!r}, {c!r}],')
        out.append('  ],')
    out.append('];')
    return '\n'.join(out)


def moon(name, table):
    out = [f'const List<List<double>> {name} = [']
    for row in table:
        out.append('  [' + ', '.join(repr(float(x)) for x in row) + '],')
    out.append('];')
    return '\n'.join(out)


print('// GENERATED by tool/gen_tables.py — do not edit by hand.')
print('//')
print('// VSOP87D Earth heliocentric series (Bretagnon & Francou 1988), units')
print('// 1e-8 rad / 1e-8 AU; and the lunar periodic terms of Meeus,')
print('// "Astronomical Algorithms" (2nd ed.) Tables 47.A and 47.B.')
print('// ignore_for_file: lines_longer_than_80_chars')
print()
print(series('vsopEarthL', Earth.VSOP87_L))
print()
print(series('vsopEarthR', Earth.VSOP87_R))
print()
print('/// D, M, M\', F, Σl (1e-6 deg), Σr (1e-3 km).')
print(moon('moonLR', Moon.PERIODIC_TERMS_LR_TABLE))
print()
print('/// D, M, M\', F, Σb (1e-6 deg).')
print(moon('moonB', Moon.PERIODIC_TERMS_B_TABLE))
