// Writes docs/CONTENT_TO_REVIEW.md from the content JSON and the Tulu UI
// strings, so the review list always matches what ships. Run from
// vesha_puzzles/:  dart run tool/gen_review_doc.dart
import 'dart:convert';
import 'dart:io';

Map<String, dynamic> j(String p) =>
    jsonDecode(File(p).readAsStringSync()) as Map<String, dynamic>;

String t(Object? v, String lang) => v is Map ? (v[lang] ?? '—') as String : '—';

void main() {
  final out = StringBuffer()
    ..writeln('# Content to review')
    ..writeln()
    ..writeln(
      'Generated by `dart run tool/gen_review_doc.dart` from `assets/` and',
    )
    ..writeln(
      '`lib/app/strings.dart`. Do not edit by hand: fix the source, mark the',
    )
    ..writeln(
      'item `"review": {"status": "approved", "notes": "<who, when>"}` and',
    )
    ..writeln('re-run the tool.')
    ..writeln()
    ..writeln('Reviewers needed:')
    ..writeln(
      '- **Yakshagana artist / scholar** (both Tenkutittu and Badagutittu if possible): stories, dress-up names, events.',
    )
    ..writeln('- **Kannada editor**: every Kannada string.')
    ..writeln(
      '- **Tulu speaker**: Tulu UI strings and guide lines; Tulu versions of stories are missing (Kannada is shown).',
    )
    ..writeln(
      '- **Parent / teacher**: tone for children (y07 implies a death in battle).',
    )
    ..writeln();

  final stories = (j('assets/content/stories.json')['stories'] as List)
      .cast<Map>();
  final pending = stories
      .where((s) => (s['review'] as Map)['status'] != 'approved')
      .toList();
  out
    ..writeln('## 1. Stories (${pending.length} of ${stories.length} pending)')
    ..writeln();
  for (final s in pending) {
    out
      ..writeln(
        '### ${s['id']} — ${t(s['title'], 'en')} / ${t(s['title'], 'kn')}',
      )
      ..writeln()
      ..writeln('**Reviewer notes:** ${(s['review'] as Map)['notes']}')
      ..writeln()
      ..writeln('**Did you know (en):** ${t(s['fact'], 'en')}  ')
      ..writeln('**Did you know (kn):** ${t(s['fact'], 'kn')}')
      ..writeln()
      ..writeln('<details><summary>English text</summary>')
      ..writeln()
      ..writeln(t(s['body'], 'en'))
      ..writeln()
      ..writeln('</details>')
      ..writeln()
      ..writeln('<details><summary>Kannada text</summary>')
      ..writeln()
      ..writeln(t(s['body'], 'kn'))
      ..writeln()
      ..writeln('</details>')
      ..writeln()
      ..writeln(
        'Tulu text: ${(s['body'] as Map).containsKey('tcy') ? 'present' : '**missing** (app shows Kannada)'}',
      )
      ..writeln();
  }

  final d = j('assets/dressup/dressup.json');
  out
    ..writeln('## 2. Dress-up names and descriptions')
    ..writeln()
    ..writeln('**Reviewer notes:** ${(d['review'] as Map)['notes']}')
    ..writeln()
    ..writeln('| Slot | Option | English | Kannada | Description (en) |')
    ..writeln('|---|---|---|---|---|');
  for (final s in (d['slots'] as List).cast<Map>()) {
    for (final o in (s['options'] as List).cast<Map>()) {
      out.writeln(
        '| ${t(s['name'], 'en')} | ${o['id']} | ${t(o['name'], 'en')} | ${t(o['name'], 'kn')} | ${t(o['about'], 'en')} |',
      );
    }
  }
  out.writeln();

  final events = (j('assets/content/events.json')['events'] as List)
      .cast<Map>();
  out
    ..writeln('## 3. Events and dates')
    ..writeln()
    ..writeln('| Event | Windows | Featured | Notes |')
    ..writeln('|---|---|---|---|');
  for (final e in events) {
    final w = (e['windows'] as List)
        .cast<Map>()
        .map((x) => '${x['from']} → ${x['to']}')
        .join('<br>');
    out.writeln(
      '| ${t(e['title'], 'en')} / ${t(e['title'], 'kn')} | $w | ${(e['featured'] as List).join(', ')} | ${(e['review'] as Map)['notes']} |',
    );
  }
  out.writeln();

  final g = j('assets/content/guide.json');
  out
    ..writeln('## 4. Vesha guide lines')
    ..writeln()
    ..writeln('| id | English | Kannada | Tulu |')
    ..writeln('|---|---|---|---|');
  for (final l in (g['lines'] as List).cast<Map>()) {
    out.writeln(
      '| ${l['id']} | ${t(l['text'], 'en')} | ${t(l['text'], 'kn')} | ${t(l['text'], 'tcy')} |',
    );
  }
  out.writeln();

  // Tulu UI strings: third argument of _t(en, kn, tcy).
  final src = File('lib/app/strings.dart').readAsStringSync();
  final re = RegExp(
    r"_t\(\s*'((?:[^'\\]|\\.)*)',\s*'((?:[^'\\]|\\.)*)',\s*'((?:[^'\\]|\\.)*)',?\s*\)",
  );
  out
    ..writeln('## 5. Tulu UI strings (Kannada script)')
    ..writeln()
    ..writeln(
      'All other UI strings fall back to Kannada when Tulu is selected.',
    )
    ..writeln()
    ..writeln('| English | Kannada | Tulu |')
    ..writeln('|---|---|---|');
  for (final m in re.allMatches(src)) {
    out.writeln('| ${m[1]} | ${m[2]} | ${m[3]} |');
  }
  out.writeln();

  final packs = (j('assets/packs/index.json')['packs'] as List).cast<String>();
  out
    ..writeln('## 6. Puzzle titles')
    ..writeln()
    ..writeln('| id | English | Kannada | Tulu |')
    ..writeln('|---|---|---|---|');
  for (final p in packs) {
    for (final z
        in (j('assets/packs/$p/pack.json')['puzzles'] as List).cast<Map>()) {
      out.writeln(
        '| ${z['id']} | ${t(z['title'], 'en')} | ${t(z['title'], 'kn')} | ${t(z['title'], 'tcy')} |',
      );
    }
  }
  out
    ..writeln()
    ..writeln('## 7. Kannada UI strings')
    ..writeln()
    ..writeln(
      'All Kannada UI strings are in `lib/app/strings.dart` (second argument of',
    )
    ..writeln(
      'each `_t(...)`). They were written for this app and need an editor\'s pass.',
    );

  File('docs/CONTENT_TO_REVIEW.md').writeAsStringSync(out.toString());
  stdout.writeln('wrote docs/CONTENT_TO_REVIEW.md');
}
